// <auto-generated />
namespace HospitalProject_Team4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class conflicsolved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conflicsolved));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121710035_conflicsolved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
